# Site
# repository: yvesdesjardins/YvesDesjardins.github.io
# favicon: images/favicon.ico

# Personal info
name: Yves Desjardins
title: Software Developer
email: YvesDesjardins@gmail.com
website: www.github.com/YvesDesjardins
# phone: +1(604)401-4639

# Social links
github_username: YvesDesjardins
linkedin_username: YvesIpDesjardins

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! Iâ€™m Yves Desjardins, a passionate software developer with expertise in building out web apps and team management

about_skills: |
  **Skills:**
    - Languages: <mark>JavaScript</mark> <mark>TypeScript</mark>
    - Frameworks/Libraries: <mark>EmberJS</mark> <mark>NodeJS</mark>
    - Systems/Databases: <mark>PostgreSQL</mark> <mark>SQL</mark> <mark>Git</mark>
    - Testing: <mark>QUnit</mark> <mark>Mirage</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  - Movies
  - Gaming (board games and video games)
  - PC building
  - Scuba diving
  - Hiking

# Footer
footer_show_references: true

# # Build settings
# remote_theme: yvesdesjardins/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
